### ISSUE TITLE
d3 download link out of date in setup.sh

### ISSUE THREAD

**Issue by joeycozza** [StanfordHCI/termite#28]
When I ran the setup, it gave me some errors concerning the d3.v3.zip that was downloaded. I looked at it, and it was only 9 kB instead of the 123 kB when I download it manually from d3's website.  I changed to url to point to the newest download, and that fixed the issue for me.

**Comment by jcchuang** [comment]
Hi Joey,

Thanks for sending in the code fixes.

I've now turned on both [Termite Data Server](http://github.com/uwdata/termite-data-server) and [Termite Visualizations](http://github.com/uwdata/termite-visualizations) repositories. Please see if those projects work for you.  Thanks!
- Jason
