### ISSUE TITLE
font-awesome.css missing in v2.0.0

### ISSUE THREAD

**Issue by erickpeirson** [StanfordHCI/termite#30]
Modeling ran successfully, and I started the server with `./web.py`

```
Extracting topic model outputs: [data/music/lda] --> [data/music/entry-0000]
--------------------------------------------------------------------------------
Importing a Mallet model...
    model = data/music/lda
    output = data/music/entry-0000
    min_term_freq = 20
    min_term_count = 5
Reading "topic-word-weights.txt" from Mallet...
Writing data to disk...
--------------------------------------------------------------------------------
ericks-air:termite-2.0.0 erickpeirson$ ./web.py 
Web server is now running at http://localhost:8888
Press "Ctrl + C" to stop the web server.
```

At `http://localhost:8888/client_src/` the Javascript log shows:

`GET http://localhost:8888/client_src/css/font-awesome.css 404 (File not found)`

**Comment by jcchuang** [comment]
Hi Erick,

The development branch wasn't intended for public release. My apologies if the git repo tag caused any confusions. I've also moved all development efforts into [Termite Data Server](http://github.com/uwdata/termite-data-server) and [Termite Visualizations](http://github.com/uwdata/termite-visualizations). Please see if those projects are more suitable for your work.

Thanks for checking out the Termite project.
- Jason
