### ISSUE TITLE
No results displayed in v2.0.0

### ISSUE THREAD

**Issue by erickpeirson** [StanfordHCI/termite#31]
Modeling ran successfully, and I started the server with `./web.py``. I navigated to`http://localhost:8888/client_src/```, and see the following:

![image](https://f.cloud.github.com/assets/3451594/2139990/0d4d957e-9346-11e3-886f-234074c46fe9.png)

The javascript log shows:

```
Uncaught TypeError: Cannot read property 'dataIDs' of null (index):105
(anonymous function) (index):105
(anonymous function) d3.js:1939
event d3.js:430
respond
```

**Comment by jcchuang** [comment]
Hi Erick,

The development branch wasn't intended for public release. My apologies if the git repo tag caused any confusions. I've also moved all development efforts into [Termite Data Server](http://github.com/uwdata/termite-data-server) and [Termite Visualizations](http://github.com/uwdata/termite-visualizations). Please see if those projects are more suitable for your work.
- Jason
